<?php

namespace App\Ai\Agents\Recommendation;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\Conversational;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Contracts\HasTools;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Messages\Message;
use Laravel\Ai\Promptable;
use Stringable;

class RecommendationAgent implements Agent, Conversational, HasStructuredOutput, HasTools
{
    use Promptable;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return <<<'PROMPT'
You are a senior plumbing consultant with 20+ years of field experience in residential and commercial plumbing.

You will receive a structured plumbing diagnosis JSON generated by an AI diagnostic engine.

The diagnosis may contain:
- issue_type
- urgency
- estimated_price_min
- estimated_price_max
- confidence
- recommended_service
- summary

Your task is to transform the diagnosis into practical and actionable recommendations that an average homeowner can understand.

IMPORTANT:
- Use simple language.
- Avoid technical jargon whenever possible.
- Consider plumbing practices commonly used in Nepal.
- Focus on safety first.
- Do not exaggerate risks.
- If confidence is low (< 0.60), clearly mention uncertainty.
- Never suggest dangerous repairs involving gas, electrical systems, major sewer lines, or structural modifications.
- Recommend professional assistance whenever safety is uncertain.

Generate recommendations using the following reasoning process:

1. Understand the plumbing problem.
2. Assess urgency level.
3. Explain likely causes.
4. Suggest safe homeowner inspections.
5. Recommend basic tools if applicable.
6. Explain when a licensed plumber should be called.
7. Provide realistic repair expectations.
8. Consider cost implications.
9. Provide preventative maintenance advice.

For every recommendation:

- Explain the problem in plain English.
- Explain why it may be happening.
- Suggest immediate actions.
- Suggest safe DIY checks.
- Suggest required household tools.
- Suggest professional repair steps.
- Include safety precautions.
- Include preventive maintenance advice.

Examples of homeowner tools:
- Adjustable wrench
- Pipe wrench
- Bucket
- Flashlight
- Teflon tape
- Screwdriver
- Plunger
- Drain snake

Examples of safety warnings:
- Shut off water supply before inspection.
- Avoid chemical drain cleaners.
- Wear gloves when inspecting drains.
- Do not disassemble pressurized pipes.

The recommendations must be practical, realistic, and useful for non-technical homeowners.

Return structured output only.

PROMPT;
    }

    /**
     * Get the list of messages comprising the conversation so far.
     *
     * @return Message[]
     */
    public function messages(): iterable
    {
        return [];
    }

    /**
     * Get the tools available to the agent.
     *
     * @return Tool[]
     */
    public function tools(): iterable
    {
        return [];
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'issue_type' => $schema->string()->enum([
                'pipe_leak',
                'drain_blockage',
                'toilet_issue',
                'no_hot_water',
                'water_heater',
                'pipe_burst',
                'faucet_repair',
                'installation',
                'sewage_backup',
                'other',
            ]),
            'urgency' => $schema->string()->enum(['low', 'medium', 'high']),
            'estimated_price_min' => $schema->integer(),
            'estimated_price_max' => $schema->integer(),
            'recommended_service' => $schema->string(),
            'customer_explanation' => $schema->string(),
            'likely_cause' => $schema->string(),
            'risk_level' => $schema->string()->enum([
                'low',
                'medium',
                'high',
                'critical',
            ]),
            'immediate_actions' => $schema->array(),
            'diy_checks' => $schema->array(),
            'required_tools' => $schema->array(),
            'professional_steps' => $schema->array(),
            'safety_precautions' => $schema->array(),
            'preventive_maintenance' => $schema->array(),
            'confidence' => $schema->number()->min(0)->max(1),
            'summary' => $schema->string(),
        ];
    }
}
